language: python
python:
  - "2.7"
# command to install dependencies
install:
  - curl -O http://googleappengine.googlecode.com/files/google_appengine_1.7.4.zip && unzip -q google_appengine_1.7.4.zip
  - pip install webtest
  - pip install pyquery
  - pip install pycrypto
  - pip install mock
# command to run tests
script:  python testrunner.py google_appengine .
